### ISSUE TITLE
Branding Guidelines

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/CG#14]
@carolinefedash If you could get these from Barney and drop them here that would be great

logo, colour schemes, font, any mood board or inspiration he might have

**Comment by carolinefedash** [comment]
Hi Matt. Here is what i have from Barney:

"There isn’t any official brand guidelines, but I could put something together if you need it. I tend to use the colours from the logo with bold simple shapes - circles, triangles, rectangles. The font is Century Gothic. There are two versions of the logo, landscape and portrait (attached)."

![cg logo small 1](https://user-images.githubusercontent.com/34347945/33773776-f44c6c70-dc30-11e7-804e-05ba10ec6578.jpg)
![cg-logo- landscape](https://user-images.githubusercontent.com/34347945/33773848-3a65bbbc-dc31-11e7-8437-833faa36bfb8.png)
