### ISSUE TITLE
Some initial designs

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/CG#17]
Hi @carolinefedash 

Hope you're well! Sorry for the late notice, but these are few ideas of how the design might look:

https://invis.io/KPEXOBQM5

Atm we haven't completely finished on the exact _flow_ of the app, so it might not make total sense in terms of the order of the screens, but any sort of feedback on the feel or anything else would be great.

We could arrange a quick 10 minute call tomorrow morning to then talk through some things? Maybe around 10:30 or 11ish?

Thanks

The team

**Comment by carolinefedash** [comment]
Hi Matt,

Wonderful - 10.30am would be good for me!

Caroline Fedash
Membership, Marketing & Communications

Create Gloucestershire 
CG supports the cultural and creative industries in Gloucestershire and introduces new people to arts, culture and creativity.

w: creategloucestershire.co.uk <http://www.creategloucestershire.co.uk/>  e: caroline@creategloucestershire.co.uk <mailto:pippa@creategloucestershire.co.uk>
t: @createglos <https://twitter.com/createglos>   f: facebook.com/creategloucestershire <http://facebook.com/creategloucestershire>

**Comment by carolinefedash** [comment]
Matt - my number is 0785 0075677.


Caroline Fedash
Membership, Marketing & Communications

Create Gloucestershire 
CG supports the cultural and creative industries in Gloucestershire and introduces new people to arts, culture and creativity.

w: creategloucestershire.co.uk <http://www.creategloucestershire.co.uk/>  e: caroline@creategloucestershire.co.uk <mailto:pippa@creategloucestershire.co.uk>
t: @createglos <https://twitter.com/createglos>   f: facebook.com/creategloucestershire <http://facebook.com/creategloucestershire>

**Comment by m4v15** [comment]
We normally use hangouts or skype cos it's a bit easier for us to talk about designs and stuff when looking at them - are you at a computer and able to do this? Not a huge problem if not, a simple phone call will be enough

**Comment by m4v15** [comment]
a link to a google hangout - https://hangouts.google.com/call/12Bye6HVbFVLT21th9eLAAEI

**Comment by carolinefedash** [comment]
Yes i am at a computer thats fine. Can you invite me?

Caroline Fedash
Membership, Marketing & Communications

Create Gloucestershire 
CG supports the cultural and creative industries in Gloucestershire and introduces new people to arts, culture and creativity.

w: creategloucestershire.co.uk <http://www.creategloucestershire.co.uk/>  e: caroline@creategloucestershire.co.uk <mailto:pippa@creategloucestershire.co.uk>
t: @createglos <https://twitter.com/createglos>   f: facebook.com/creategloucestershire <http://facebook.com/creategloucestershire>

**Comment by m4v15** [comment]
posting it again in case it got lost from your reply: https://hangouts.google.com/call/12Bye6HVbFVLT21th9eLAAEI

**Comment by carolinefedash** [comment]
I have managed to download hangouts but don't seem to be able to access your call!
Caroline Fedash
Membership, Marketing & Communications

Create Gloucestershire 
CG supports the cultural and creative industries in Gloucestershire and introduces new people to arts, culture and creativity.

w: creategloucestershire.co.uk <http://www.creategloucestershire.co.uk/>  e: caroline@creategloucestershire.co.uk <mailto:pippa@creategloucestershire.co.uk>
t: @createglos <https://twitter.com/createglos>   f: facebook.com/creategloucestershire <http://facebook.com/creategloucestershire>

**Comment by m4v15** [comment]
oh you shouldn't have to download hangouts the link should just work, although only with a gmail account, lets do a phone call instead
